MCS1.CreateClientTypeHook("DrawOverlay", "DrawOverlay")
MCS1.CreateClientTypeHook("PostDrawOpaqueRenderables", "PostDrawOpaqueRenderables")
MCS1.CreateClientTypeHook("PostDrawTranslucentRenderables", "PostDrawTranslucentRenderables")
MCS1.CreateClientTypeHook("RenderScreenspaceEffects", "RenderScreenspaceEffects")
MCS1.CreateClientTypeHook("SetupWorldFog", "SetupFog")
MCS1.CreateClientTypeHook("SetupSkyboxFog", "SetupFog")